# Generated by Django 2.0 on 2017-12-24 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256, null=True)),
                ('Authcontent', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('initalnum', models.IntegerField(null=True)),
                ('actualnum', models.IntegerField(null=True)),
                ('prefix', models.CharField(max_length=256, null=True)),
                ('suffix', models.CharField(max_length=256, null=True)),
                ('pplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynatag.Application')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, null=True)),
                ('address_street', models.CharField(max_length=256, null=True)),
                ('address_city', models.CharField(max_length=256, null=True)),
                ('address_province', models.CharField(max_length=256, null=True)),
                ('address_country', models.CharField(max_length=256, null=True)),
                ('user_regid', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynatag.User'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynatag.User'),
        ),
    ]
