# Generated by Django 2.0 on 2017-12-24 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynatag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='pplication',
            new_name='aplication',
        ),
    ]
