# Generated by Django 2.0 on 2017-12-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynatag', '0002_auto_20171224_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='aplication',
            new_name='application',
        ),
    ]
