# Generated by Django 2.0 on 2017-12-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynatag', '0004_auto_20171225_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
