# Generated by Django 2.0 on 2018-01-04 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dynatag', '0005_auto_20171228_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256, null=True)),
                ('Authcontent', models.CharField(max_length=256, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='Authcontent',
        ),
        migrations.RemoveField(
            model_name='application',
            name='source',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='appname',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='apptoken',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='appuri',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='userapp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynatag.Userapp'),
        ),
    ]
