# Generated by Django 2.0 on 2018-01-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynatag', '0006_auto_20180104_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tokenrefresh_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
