# Generated by Django 2.0 on 2018-01-31 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynatag', '0007_application_tokenrefresh_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='userapp',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuration',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynatag.Application'),
        ),
        migrations.DeleteModel(
            name='Userapp',
        ),
    ]
