# Generated by Django 2.0 on 2018-01-31 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynatag', '0008_auto_20180131_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='owner',
        ),
    ]
