# Generated by Django 2.0 on 2018-01-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynatag', '0009_auto_20180131_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='owner',
            new_name='user',
        ),
    ]
